# Generated by Django 3.2.5 on 2022-11-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=40)),
                ('fee', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='transport',
        ),
    ]
