# Generated by Django 3.2.5 on 2022-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20221107_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.IntegerField()),
                ('plane', models.IntegerField()),
                ('ola', models.IntegerField()),
            ],
        ),
    ]
